server:
  port: 8888   # default port for config server

spring:
  application:
    name: configserver

  profiles:
    active: native   # force native profile

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config


